# Generated by Django 3.0.2 on 2021-05-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_auto_20210501_1441'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
