# Generated by Django 3.0.2 on 2021-05-01 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
