# Generated by Django 3.0.2 on 2021-05-01 18:15

from django.db import migrations, models
import django.db.models.deletion
import musicapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file_location', models.CharField(max_length=200)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.Album')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(musicapp.models.RecommendationType['PLAYLIST'], 'Playlist'), (musicapp.models.RecommendationType['ALBUM'], 'Album'), (musicapp.models.RecommendationType['SONG'], 'Song')], max_length=100)),
                ('item_id', models.IntegerField()),
                ('recommended_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_by', to='musicapp.User')),
                ('recommended_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to', to='musicapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.User')),
            ],
        ),
    ]
