# Generated by Django 3.0.2 on 2021-05-01 18:48

from django.db import migrations, models
import django.db.models.deletion
import musicapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_auto_20210501_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicapp.User'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommended_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommended_by', to='musicapp.User'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommended_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommended_to', to='musicapp.User'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicapp.Album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicapp.Genre'),
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(musicapp.models.UserRatingType['PLAYLIST'], 'Playlist'), (musicapp.models.UserRatingType['ALBUM'], 'Album'), (musicapp.models.UserRatingType['SONG'], 'Song')], max_length=100)),
                ('item_id', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='SongArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicapp.Artist')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicapp.Song')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicapp.Playlist')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicapp.Song')),
            ],
        ),
    ]
